# Generated by Django 3.1.5 on 2021-06-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transactionDate', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
