# Generated by Django 3.1.5 on 2021-06-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('needs', 'Needs'), ('wants', 'Wants'), ('others', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
